Invoke preflight in a thread with controlled and larger stack (#8)
* Invoke preflight in a thread with controlled and larger stack
* Use spawn_scoped, instead:

Growing the stack from within the same thread actually also ruins
Go's own stack management, leading to panics later:

> fatal error: morestack on g0

So we actually do need the thread. We'll use spawn_scoped this time,
though, so we don't need the hairy transmutation stuff.

* Bump protocol upgrade test timing threshold

(cherry picked from commit f84ba9621fb82656ed1d5487212f268f6d64c5cf)